### ISSUE TITLE
oddb2xml not yet working with Ruby 3.1.0

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb2xml#56]
```
~/.software/oddb2xml> ruby -v
ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [x86_64-linux]
```
`~/.software/oddb2xml> oddb2xml --help`
results in
```
/home/zeno/.rbenv/versions/3.1.0/lib/ruby/3.1.0/psych/class_loader.rb:99:in `find': Tried to load unspecified class: Struct::GalenicGroup (Psych::DisallowedClass)
        from /home/zeno/.rbenv/versions/3.1.0/lib/ruby/3.1.0/psych/class_loader.rb:28:in `load'
        from /home/zeno/.rbenv/versions/3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:424:in `resolve_class'
        from /home/zeno/.rbenv/versions/3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:171:in `visit_Psych_Nodes_Mapping'
        from /home/zeno/.rbenv/versions/3.1.0/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
        from /home/zeno/.rbenv/versions/3.1.0/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
        from /home/zeno/.rbenv/versions/3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
        from /home/zeno/.rbenv/versions/3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:345:in `block in revive_hash'
        from /home/zeno/.rbenv/versions/3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `each'
        from /home/zeno/.rbenv/versions/3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `each_slice'
        from /home/zeno/.rbenv/versions/3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `revive_hash'
        from /home/zeno/.rbenv/versions/3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:167:in `visit_Psych_Nodes_Mapping'
        from /home/zeno/.rbenv/versions/3.1.0/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
        from /home/zeno/.rbenv/versions/3.1.0/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
        from /home/zeno/.rbenv/versions/3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
        from /home/zeno/.rbenv/versions/3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:318:in `visit_Psych_Nodes_Document'
        from /home/zeno/.rbenv/versions/3.1.0/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
        from /home/zeno/.rbenv/versions/3.1.0/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
        from /home/zeno/.rbenv/versions/3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
        from /home/zeno/.rbenv/versions/3.1.0/lib/ruby/3.1.0/psych.rb:335:in `safe_load'
        from /home/zeno/.rbenv/versions/3.1.0/lib/ruby/3.1.0/psych.rb:370:in `load'
        from /home/zeno/.rbenv/versions/3.1.0/lib/ruby/3.1.0/psych.rb:671:in `block in load_file'
        from /home/zeno/.rbenv/versions/3.1.0/lib/ruby/3.1.0/psych.rb:670:in `open'
        from /home/zeno/.rbenv/versions/3.1.0/lib/ruby/3.1.0/psych.rb:670:in `load_file'
        from /home/zeno/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/oddb2xml-2.7.5/lib/oddb2xml/calc.rb:98:in `<class:Calc>'
        from /home/zeno/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/oddb2xml-2.7.5/lib/oddb2xml/calc.rb:23:in `<module:Oddb2xml>'
        from /home/zeno/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/oddb2xml-2.7.5/lib/oddb2xml/calc.rb:5:in `<top (required)>'
        from <internal:/home/zeno/.rbenv/versions/3.1.0/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/zeno/.rbenv/versions/3.1.0/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/zeno/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/oddb2xml-2.7.5/lib/oddb2xml/builder.rb:3:in `<top (required)>'
        from <internal:/home/zeno/.rbenv/versions/3.1.0/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/zeno/.rbenv/versions/3.1.0/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/zeno/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/oddb2xml-2.7.5/lib/oddb2xml/cli.rb:1:in `<top (required)>'
        from <internal:/home/zeno/.rbenv/versions/3.1.0/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/zeno/.rbenv/versions/3.1.0/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/zeno/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/oddb2xml-2.7.5/lib/oddb2xml.rb:2:in `<top (required)>'
        from <internal:/home/zeno/.rbenv/versions/3.1.0/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/zeno/.rbenv/versions/3.1.0/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/zeno/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/oddb2xml-2.7.5/bin/oddb2xml:8:in `<top (required)>'
        from /home/zeno/.rbenv/versions/3.1.0/bin/oddb2xml:25:in `load'
        from /home/zeno/.rbenv/versions/3.1.0/bin/oddb2xml:25:in `<main>'
```

**Comment by zdavatz** [comment]
2.8.0 works with Ruby 3.1.0
