### ISSUE TITLE
`gem install oddb2xml-2.8.0` results in `unknown keyword: :permitted_classes (ArgumentError)` - Ruby 3.0.0 Problem

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb2xml#67]
1. `gem install oddb2xml-2.8.0`
2. results in
```
/opt/ywesee/.rbenv/versions/3.0.0/lib/ruby/3.0.0/psych.rb:274:in `load': unknown keyword: :permitted_classes (ArgumentError)
        from /opt/ywesee/.rbenv/versions/3.0.0/lib/ruby/3.0.0/psych.rb:582:in `block in load_file'
        from /opt/ywesee/.rbenv/versions/3.0.0/lib/ruby/3.0.0/psych.rb:581:in `open'
        from /opt/ywesee/.rbenv/versions/3.0.0/lib/ruby/3.0.0/psych.rb:581:in `load_file'
        from /opt/ywesee/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/oddb2xml-2.8.0/lib/oddb2xml/calc.rb:98:in `<class:Calc>'
        from /opt/ywesee/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/oddb2xml-2.8.0/lib/oddb2xml/calc.rb:23:in `<module:Oddb2xml>'
        from /opt/ywesee/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/oddb2xml-2.8.0/lib/oddb2xml/calc.rb:5:in `<top (required)>'
        from <internal:/opt/ywesee/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/opt/ywesee/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /opt/ywesee/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/oddb2xml-2.8.0/lib/oddb2xml/builder.rb:3:in `<top (required)>'
        from <internal:/opt/ywesee/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/opt/ywesee/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /opt/ywesee/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/oddb2xml-2.8.0/lib/oddb2xml/cli.rb:1:in `<top (required)>'
        from <internal:/opt/ywesee/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/opt/ywesee/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /opt/ywesee/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/oddb2xml-2.8.0/lib/oddb2xml.rb:2:in `<top (required)>'
        from <internal:/opt/ywesee/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/opt/ywesee/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /opt/ywesee/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/oddb2xml-2.8.0/bin/oddb2xml:8:in `<top (required)>'
        from /opt/ywesee/.rbenv/versions/3.0.0/bin/oddb2xml:23:in `load'
        from /opt/ywesee/.rbenv/versions/3.0.0/bin/oddb2xml:23:in `<main>'
```
3. Gem was built with `bundle exec rake gem`
4. Ruby Version 3.0.0

**Comment by zdavatz** [comment]
works with Ruby 3.1.0
