### ISSUE TITLE
Header Hash Error on Ubuntu with Ruby 3.3.0

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb2xml#92]
1. Running `oddb2xml -e`
2. with Ruby 3.3.0 and 3.2.0
3. on Ubuntu
4. results in
5. ![headerHash](https://github.com/zdavatz/oddb2xml/assets/4953/91907b51-5bba-4aab-9f79-21ee03dcd58f)

**Comment by zdavatz** [comment]
```
/Users/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/httpi-2.5.0/lib/httpi/request.rb:67:in `headers': uninitialized constant Rack::Utils::HeaderHash (NameError)

      @headers ||= Rack::Utils::HeaderHash.new
                              ^^^^^^^^^^^^
Did you mean?  Rack::Headers
	from /Users/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/httpi-2.5.0/lib/httpi/adapter/net_http.rb:202:in `request_client'
	from /Users/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/httpi-2.5.0/lib/httpi/adapter/net_http.rb:91:in `block in do_request'
	from /Users/zdavatz/.rbenv/versions/3.2.0/lib/ruby/3.2.0/net/http.rb:1238:in `start'
	from /Users/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/httpi-2.5.0/lib/httpi/adapter/net_http.rb:89:in `do_request'
	from /Users/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/httpi-2.5.0/lib/httpi/adapter/net_http.rb:38:in `request'
	from /Users/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/httpi-2.5.0/lib/httpi.rb:161:in `request'
	from /Users/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/httpi-2.5.0/lib/httpi.rb:127:in `get'
	from /Users/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/wasabi-3.7.0/lib/wasabi/resolver.rb:45:in `load_from_remote'
	from /Users/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/wasabi-3.7.0/lib/wasabi/resolver.rb:35:in `resolve'
	from /Users/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/wasabi-3.7.0/lib/wasabi/document.rb:144:in `xml'
	from /Users/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/wasabi-3.7.0/lib/wasabi/document.rb:162:in `parse'
	from /Users/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/wasabi-3.7.0/lib/wasabi/document.rb:149:in `parser'
	from /Users/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/wasabi-3.7.0/lib/wasabi/document.rb:66:in `soap_actions'
	from /Users/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/savon-2.12.1/lib/savon/operation.rb:22:in `ensure_exists!'
	from /Users/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/savon-2.12.1/lib/savon/operation.rb:15:in `create'
	from /Users/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/savon-2.12.1/lib/savon/client.rb:32:in `operation'
	from /Users/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/savon-2.12.1/lib/savon/client.rb:36:in `call'
	from /Users/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/oddb2xml-2.9.2/lib/oddb2xml/downloader.rb:276:in `download'
	from /Users/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/oddb2xml-2.9.2/lib/oddb2xml/cli.rb:302:in `download'
	from /Users/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/oddb2xml-2.9.2/lib/oddb2xml/cli.rb:68:in `block in run'
	from /Users/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/oddb2xml-2.9.2/lib/oddb2xml/cli.rb:67:in `each'
	from /Users/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/oddb2xml-2.9.2/lib/oddb2xml/cli.rb:67:in `run'
	from /Users/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/oddb2xml-2.9.2/bin/oddb2xml:38:in `<top (required)>'
	from /Users/zdavatz/.rbenv/versions/3.2.0/bin/oddb2xml:25:in `load'
	from /Users/zdavatz/.rbenv/versions/3.2.0/bin/oddb2xml:25:in `<main>'
```

**Comment by zdavatz** [comment]
1. This looks like a `rack` version problem.
2. Seems to work with Rack version: `rack (3.0.8, 3.0.4.1)`g
3. But not with `rack (3.1.5)

**Comment by zdavatz** [comment]
also see: https://chatgpt.com/share/6f552ec1-49b6-4b84-a12a-1486870c8638
